Repository luiscarlosjunior/aulas-graduacao, pull requests merged in 2021-04, with the labels that each got.

#42 Added new link
  Outros/POO UML/README.md
Labels: bug, documentation

#45 Exemplos simples em python
  Data science/python/intro/01-Inicio_python.ipynb
Labels: bug, good first issue

#46 Added new scripts for postgre
  Banco de dados/SQL/postgre/01-intro/banco-inicial.sql
  Banco de dados/SQL/postgre/01-intro/dados-aula-2.sql
  Banco de dados/SQL/postgre/01-intro/relatorios-aula-2.sql
  Outros/POO UML/Aula 1/models-drawio/Diagrama de classes.svg
Labels: database script

#47 Added new data
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/.vscode/settings.json
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/Cliente/Cliente.cs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/Program.cs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/Servicos/Conta.cs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/Servicos/ContaPoupanca.cs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/bin/Debug/netcoreapp3.1/poo_conta.deps.json
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/bin/Debug/netcoreapp3.1/poo_conta.dll
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/bin/Debug/netcoreapp3.1/poo_conta.pdb
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/bin/Debug/netcoreapp3.1/poo_conta.runtimeconfig.dev.json
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/bin/Debug/netcoreapp3.1/poo_conta.runtimeconfig.json
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.AssemblyInfo.cs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.AssemblyInfoInputs.cache
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.assets.cache
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.csproj.CoreCompileInputs.cache
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.csproj.FileListAbsolute.txt
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.csprojAssemblyReference.cache
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.dll
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.genruntimeconfig.cache
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/Debug/netcoreapp3.1/poo_conta.pdb
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/poo_conta.csproj.nuget.dgspec.json
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/poo_conta.csproj.nuget.g.props
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/poo_conta.csproj.nuget.g.targets
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/project.assets.json
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/obj/project.nuget.cache
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/c-sharp/poo_conta_01/poo_conta.csproj
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/.gitignore
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/.classpath
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/.gitignore
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/.project
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/.settings/org.eclipse.jdt.core.prefs
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/AbrirConta.class
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/AbrirConta.java
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/Cliente.java
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/Conta.class
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/Conta.java
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/ContaPoupanca.class
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/ContaPoupanca.java
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/principal.class
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Conta/src/principal.java
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Exemplos/01 - HelloWorld/olamundo.java
  Outros/POO UML/Codigos/Aula 1/Exemplo banco/java/Exemplos/02 - Variaveis/App.java
Labels: documentation, enhancement

#49 Added new models for the the database class
  Banco de dados/Modelagem Banco de Dados/Aula 02/script aula 02 - Empresa Fisico.sql
  Banco de dados/Modelagem Banco de Dados/Aula 03/Modelo/Generalizacao_01.brM3
  Banco de dados/Modelagem Banco de Dados/Aula 03/Modelo/Generalizacao_02.brM3
  Banco de dados/Modelagem Banco de Dados/Aula 03/Modelo/Generalizacao_03.brM3
  Banco de dados/Modelagem Banco de Dados/Aula 03/Modelo/Generalizacao_04.brM3
  Banco de dados/Modelagem Banco de Dados/Software/config.chc
Labels: Sample Programming

#51 Added new model that represent multiple inheritance
  Banco de dados/Modelagem Banco de Dados/Aula 03/Modelo/Generalizacao_05.brM3
  Banco de dados/Modelagem Banco de Dados/Software/config.chc
Labels: database script

#54 Novos exemplos de POO em PHP
  Programação/Back-End PHP/03/banco.php
  Programação/Back-End PHP/03/mundocao/Cachorro.php
  Programação/Back-End PHP/03/mundocao/Principal.php
  Programação/Back-End PHP/03/mundocao/construtor/Cachorro.php
  Programação/Back-End PHP/03/mundocao/construtor/Pinscher.php
  Programação/Back-End PHP/03/mundocao/construtor/Poddle.php
  Programação/Back-End PHP/03/mundocao/construtor/Principal.php
  Programação/Back-End PHP/03/mundocao/encapsulamento/Cachorro.php
  Programação/Back-End PHP/03/mundocao/encapsulamento/Pinscher.php
  Programação/Back-End PHP/03/mundocao/encapsulamento/Poddle.php
  Programação/Back-End PHP/03/mundocao/encapsulamento/Principal.php
  Programação/Back-End PHP/03/mundocao/heranca/Cachorro.php
  Programação/Back-End PHP/03/mundocao/heranca/Pinscher.php
  Programação/Back-End PHP/03/mundocao/heranca/Principal.php
  Programação/Back-End PHP/03/mundocao/heranca/Principal_function.php
  Programação/Back-End PHP/03/mundocao/heranca/poddle.php
  Programação/Back-End PHP/03/mundocao/polimorfismo/Cachorro.php
  Programação/Back-End PHP/03/mundocao/polimorfismo/Pinscher.php
  Programação/Back-End PHP/03/mundocao/polimorfismo/Poddle.php
  Programação/Back-End PHP/03/mundocao/polimorfismo/Principal.php
  Programação/Back-End PHP/03/mundocao/simples/Cachorro.php
  Programação/Back-End PHP/03/mundocao/simples/Principal.php
Labels: Refactored, Sample Programming

#55 Novos exemplos de POO em PHP
  Programação/Back-End PHP/03/mundocao.zip
  Programação/Back-End PHP/03/mundocao/Cachorro.php
  Programação/Back-End PHP/03/mundocao/Principal.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/abstracao/Cachorro.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/abstracao/principal.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/construtor/Cachorro.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/construtor/Pinscher.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/construtor/Poddle.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/construtor/principal.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/encapsulamento/Cachorro.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/encapsulamento/Pinscher.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/encapsulamento/Poddle.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/encapsulamento/principal.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/heranca/Cachorro.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/heranca/Pinscher.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/heranca/Poddle.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/heranca/principal.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/polimorfismo/Cachorro.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/polimorfismo/Pinscher.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/polimorfismo/Poddle.php
  Programação/Back-End PHP/03/mundocao/feitos em aula/polimorfismo/principal.php
Labels: Sample Programming

#60 Rodrigo py
  Data science/python/intro/.ipynb_checkpoints/1 - Introdução à linguagem Python-checkpoint.ipynb
  Data science/python/intro/1 - Introdução à linguagem Python.ipynb
Labels: programming topics

#69 Se aceito, este commit irá add arquivos gitignore
  .gitignore
  Data science/python/.gitignore
  Programação/.gitignore
  Programação/Java/.gitignore
Labels: Refactored, documentation

#70 Arquivo zip desnecessário
  Banco de dados/Stored Procedure/PLSQL - Oracle/Exemplos.zip
Labels: bug

#77 Se aceito, este commit irá apresentar orientação a objetos
  Programação/Java/000-Exemplos/05-Introdução à orientação OOP
  Programação/Java/000-Exemplos/06-Métodos
  Programação/Java/000-Exemplos/07-Construtores
  Programação/Java/000-Exemplos/08-Arrays
  Programação/Java/000-Exemplos/09-Pilares da OOP (Herança, polimorfismo, abstração e encapsulamento)
  Programação/Java/000-Exemplos/10-Interfaces
Labels: Sample Programming, programming topics

#81 Se aceito, este commit irá criar um arquivo de documentação sobre variáveis
  Programação/Java/Variaveis.md
Labels: documentation

#82 Atualizando a documentação dos tipos de dados
  Programação/Java/TiposDados.md
Labels: documentation

#83 Atualização da tabela de tipos de dados
  Programação/Java/TiposDados.md
Labels: documentation

#84 Se este commit for aceito, será adicionado o tópico sobre tipos de dados
  Programação/Java/Aspectos Fundamentais Java
Labels: documentation

#85 Renomeando o tipo
  Programação/Java/AspectosFundamentaisJava.md
Labels: documentation

#86 Atualização da formatação da documentação em java
  Programação/Java/AspectosFundamentaisJava.md
Labels: documentation

#87 Atualizado o conteúdo essencial em java
  Programação/Java/Variaveis.md
Labels: documentation

#92 Create Operadores
  Programação/Java/Operadores.md
Labels: documentation

#94 Update Operators
  Programação/Java/Operadores.md
Labels: documentation, programming topics

#97 Atualizando a branch master
  Outros/POO UML/Codigos/Aula 4/Exemplo Aula/Exemplo_Conta_abstract/src/conceitosJava/ControleFluxo.java
  Outros/POO UML/Codigos/Aula 4/Exemplo Aula/Exemplo_Conta_abstract/src/conceitosJava/EstruturaRepeticao.java
  Outros/POO UML/Codigos/Aula 4/Exemplo Aula/Exemplo_Conta_abstract/src/conceitosJava/TiposDados.java
  Programação/Java/02-conceitos/Controle de Fluxo if/ExemploIR2019.java
  Programação/Java/02-conceitos/Controle de Fluxo if/ExemplosControleFluxo.java
  Programação/Java/02-conceitos/Controle de Fluxo if/TestaCondicional.java
  Programação/Java/02-conceitos/Controle de Fluxo if/TestaCondicional2.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/EstruturaRepeticao.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/Fatorial.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/MultiplosDeTresAteCem.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/TestaFor.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/TestaLaco2.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/TestaLacos.java
  Programação/Java/02-conceitos/Controle de Fluxo repeticao/TestaWhile.java
  Programação/Java/02-conceitos/HelloWorld.java
  Programação/Java/02-conceitos/Tipos de dados/TestaCaracteres.java
  Programação/Java/02-conceitos/Tipos de dados/TestaConversao.java
  Programação/Java/02-conceitos/Tipos de dados/TestaEscopo.java
  Programação/Java/02-conceitos/Tipos de dados/TestaPontoFlutuante.java
  Programação/Java/02-conceitos/Tipos de dados/TiposDados.java
  Programação/Java/02-conceitos/conceitosJava/.classpath
  Programação/Java/02-conceitos/conceitosJava/.project
  Programação/Java/02-conceitos/conceitosJava/.settings/org.eclipse.jdt.core.prefs
  Programação/Java/02-conceitos/conceitosJava/bin/conceitosJava/Conceitos.class
  Programação/Java/02-conceitos/conceitosJavaII/build.xml
  Programação/Java/02-conceitos/conceitosJavaII/manifest.mf
  Programação/Java/02-conceitos/conceitosJavaII/nbproject/build-impl.xml
  Programação/Java/02-conceitos/conceitosJavaII/nbproject/genfiles.properties
  Programação/Java/02-conceitos/conceitosJavaII/nbproject/project.properties
  Programação/Java/02-conceitos/conceitosJavaII/nbproject/project.xml
  Programação/Java/02-conceitos/conceitosSimples/build.xml
  Programação/Java/02-conceitos/conceitosSimples/build/classes/.netbeans_automatic_build
  Programação/Java/02-conceitos/conceitosSimples/build/classes/.netbeans_update_resources
  Programação/Java/02-conceitos/conceitosSimples/build/classes/javaapplication1/JavaApplication1.class
  Programação/Java/02-conceitos/conceitosSimples/manifest.mf
  Programação/Java/02-conceitos/conceitosSimples/nbproject/build-impl.xml
  Programação/Java/02-conceitos/conceitosSimples/nbproject/genfiles.properties
  Programação/Java/02-conceitos/conceitosSimples/nbproject/private/private.properties
  Programação/Java/02-conceitos/conceitosSimples/nbproject/project.properties
  Programação/Java/02-conceitos/conceitosSimples/nbproject/project.xml
  Programação/Java/02-conceitos/exericios/Exercicios.java
  Programação/Java/Apostila/AspectosFundamentaisJava.md
  Programação/Java/Apostila/Operadores.md
  Programação/Java/Apostila/TiposDados.md
  Programação/Java/Apostila/Variaveis.md
Labels: Refactored, documentation, programming topics

#98 Fixed bug
  Programação/Java/Apostila/Operadores.md
Labels: bug

#99 Criar documentação de introdução do java
  Programação/Java/Apostila/IntroducaoJava.md
Labels: documentation, programming topics

#105 Atualizar
  Programação/Java/Variaveis.md
Labels: documentation

#107 Created Introduçao PHP
  Programação/Back-End PHP/IntroducaoPHP.md
Labels: Sample Programming, documentation

#108 Criado arquivos sintaxe básica
  Programação/Back-End PHP/SintaxeBasica.md
Labels: documentation

#109 Criar PHPTipos
  Programação/Back-End PHP/TiposPHP.md
Labels: documentation

#111 Consertando gramática
  Programação/Back-End PHP/TiposPHP.md
Labels: documentation, programming topics

#114 Se este commit for aceito, irá adicionar uma introdução sobre SQL
  Banco de dados/Stored Procedure/PLSQL - Oracle/SQLBasico.md
Labels: database script, documentation

#115 Adicionando uma lista de comandos
  Banco de dados/Stored Procedure/PLSQL - Oracle/SQLBasico.md
Labels: database script, documentation

#116 Update introdução Java
  Programação/Java/Apostila/IntroducaoJava.md
Labels: Refactored, Sample Programming, documentation

#117 Adicionado a descrição do tipo Boolean
  Programação/Back-End PHP/TiposPHP.md
Labels: documentation

#118 Acrescentando a descrição do tipo int
  Programação/Back-End PHP/TiposPHP.md
Labels: documentation

#120 Se aceito, irá criar a documentação intro PLSQL
  Banco de dados/Stored Procedure/PLSQL - Oracle/introducao.md
Labels: database script, documentation

#121 Introduzido uma seção sobre o bloco PLSQL
  Banco de dados/Stored Procedure/PLSQL - Oracle/introducao.md
Labels: database script, documentation

#122 Adicionado o conceito de variáveis
  Banco de dados/Stored Procedure/PLSQL - Oracle/introducao.md
Labels: database script, documentation

#123 Foi adicionado uma nova seção de operadores
  Banco de dados/Stored Procedure/PLSQL - Oracle/introducao.md
Labels: database script, documentation

#124 Adicionado aula sql server
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 05/manipulação string/Exemplo chr.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 05/manipulação string/Operadores String.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/Exemplos/Uso de caracteres de escape.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/entrada usuario/01-Exemplo dos dois pontos.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/entrada usuario/02-Exemplo decisao com dados.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/entrada usuario/03-Uso da entrada por e comercial.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estrutura de repeticao/Exemplo Inserir dados com loop for.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estrutura de repeticao/Exemplo laço de repeticao.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estruturas de controle/00-loop.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estruturas de controle/01-while.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estruturas de controle/02-for_loop.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estruturas de controle/04 - Operadores.sql
  Banco de dados/Stored Procedure/PLSQL - Oracle/Aula 06/estruturas de controle/Exemplo estrutura de decisão.sql
Labels: bug, documentation
